#!/bin/zsh

# Temporary hack to get antibody to work on WSL
if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
  export PATH=${HOME}/.local/bin:$PATH
fi

source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt

SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  char          # Prompt character
)

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Exports
export SPACESHIP_PROMPT_ADD_NEWLINE=false
export SPACESHIP_PROMPT_SEPARATE_LINE=false
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

if [[ "$OSTYPE" == "darwin"* ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
  eval "$(nodenv init -)"

  # Aliases
  alias git=hub
  alias jp=jupyter-notebook

  #VSCode Shortcut
  code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

elif grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
  # WSL Specific Configuration
fi
