#!/bin/zsh
source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt

SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  char          # Prompt character
)

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

if [[ "$OSTYPE" == "darwin"* ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
  eval "$(nodenv init -)"
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
  export ROS_VM="/media/psf/ROS_VM"
  source /opt/ros/kinetic/setup.zsh
fi

# Aliases
alias git=hub
alias jp=jupyter-notebook

# Exports
export SPACESHIP_PROMPT_ADD_NEWLINE=false
export SPACESHIP_PROMPT_SEPARATE_LINE=false
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

export LDFLAGS="-L/usr/local/opt/openblas/lib"
export CPPFLAGS="-I/usr/local/opt/openblas/include"
export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"

export GOPATH=$HOME/software/go
